#!/usr/bin/env bash

# This script should generate all the possible build combinations of
# `nodeos-barebones` and test them by being able to exec a Node.js REPL. In some
# cases this could not be fully possible and so the tests should be improved in
# the future


BUILD="npm run build --no-spin"
TEST="npm test"


eval MACHINE=pc BITS=32 $BUILD && $TEST || exit 1
eval MACHINE=pc BITS=64 $BUILD && $TEST || exit 2
eval MACHINE=raspi2     $BUILD          || exit 3


#
# Upload release to GitHub
#

if [ "$BRANCH_NAME" = "master" ]; then
  if [ "$GITHUB_TOKEN" ]; then
    prebuild --upload-all $GITHUB_TOKEN || exit 10
  fi

  if [ "$NPM_TOKEN" ]; then
    ci-publish
  fi
fi
