#!/usr/bin/env node

var manager = require('download-manager')


// Source versions

const INIT_VERSION  = "master"
const LINUX_VERSION = "4.7.1"


// Source URLs

const INIT_URL  = "https://github.com/piranna/nodeos-init/archive/"+INIT_VERSION+".tar.gz"
const LINUX_URL = "https://www.kernel.org/pub/linux/kernel/v4.x/linux-"+LINUX_VERSION+".tar.gz"


// Checksums

const LINUX_SHA256 = '3bf449c75723494a55e623afb4e50bca5795f213a51c87e6c031a72cc74f7359'


// Patch Linux kernel to add Unicode BMP support on `fbcon`
const LINUX_CJKTTY_VERSION = "4.4"
const LINUX_CJKTTY_PATCH = "https://raw.githubusercontent.com/NodeOS/cjktty-patch/master/patches/linux-"+LINUX_CJKTTY_VERSION+"-cjktty.diff"


//
// Node.js
//

var downloads =
[
  {
    name: 'init',
    url: INIT_URL
  },
  {
    name: 'linux',
    url: LINUX_URL,
    sha256: LINUX_SHA256,
    patch:
    [
      {
        url: LINUX_CJKTTY_PATCH,
        strip: 1
      },
      {
        url: 'resources/linux-vagrant.patch',
        strip: 1
      }
    ]
  }
]


manager(downloads, {path: 'deps'}, function(error)
{
  if(error)
  {
    console.trace(error)
    process.exit(1)
  }
})
